openapi: 3.0.0
info:
  description: This API provides event stats
  version: "1.0.0"
  title: Stats API
  contact:
    email: nfakhrurradi@my.bcit.ca

paths:
  /stats:
    get:
      summary: Gets the event stats
      operationId: app.get_stats
      description: Gets delivery and schedule processed statistics
      responses:
        '200':
          description: Successfully returned a list of delishery event stats
          content:
            application/json:
              schema:
                type: object
                items: 
                  $ref: '#/components/schemas/DelisheryStats'
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string

components:
  schemas:
    DelisheryStats:
      type: object
      required:
        - num_of_deliveries
        - num_of_schedules
        - total_delivery_items
        - total_scheduled_deliveries
      properties:
        num_of_deliveries:
          type: integer
          example: 1000
        num_of_schedules:
          type: integer
          example: 1000
        total_delivery_items:
          type: integer
          example: 10
        total_scheduled_deliveries:
          type: integer
          example: 5
