openapi: 3.0.0
info:
  description: This API provides event logger stats
  version: "1.0.0"
  title: Stats API
  contact:
    email: nfakhrurradi@my.bcit.ca

paths:
  /event_stats:
    get:
      summary: Gets the event logger stats
      operationId: app.get_event_stats
      description: Gets delivery and schedule processed statistics
      responses:
        '200':
          description: Successfully returned a list of delishery event stats
          content:
            application/json:
              schema:
                type: object
                items: 
                  $ref: '#/components/schemas/EventLoggerStats'
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string

components:
  schemas:
    EventLoggerStats:
      type: object
      required:
        - "0001"
        - "0002"
        - "0003"
        - "0004"
      properties:
        "0001":
          type: integer
          example: 1000
        "0002":
          type: integer
          example: 1000
        "0003":
          type: integer
          example: 10
        "0004":
          type: integer
          example: 5
      example:
        "0001": 10
        "0002": 11
        "0003": 8
        "0004": 2
